"""
Financial Reports Module
Generates P&L, Balance Sheet, and Tax Reports.

⚠️ IMPORTANT DISCLAIMER:
These reports are provided for informational purposes only and should be 
verified by a qualified accountant before being used for tax filing, 
financial decisions, or regulatory compliance. The software does not 
guarantee accuracy and is not a substitute for professional accounting advice.
"""

from datetime import datetime, date, timedelta
from typing import Dict, List, Optional, Tuple
from decimal import Decimal
from database import get_db, get_db_config


def get_date_diff_sql(date1: str, date2: str) -> str:
    """Get the SQL for calculating date difference based on database type."""
    config = get_db_config()
    if config.get('type') == 'mysql':
        # MySQL: DATEDIFF returns days difference
        return f"DATEDIFF({date1}, {date2})"
    else:
        # SQLite: julianday returns days difference
        return f"julianday({date1}) - julianday({date2})"


class FinancialReports:
    """
    Generate financial reports including P&L, Balance Sheet, and Tax Reports.
    
    ⚠️ DISCLAIMER: All reports generated by this module should be reviewed and 
    verified by a qualified accountant before use for any official purposes.
    """
    
    DISCLAIMER = """
    ⚠️ IMPORTANT: These reports are for informational purposes only and have not 
    been audited. They should be verified by a qualified accountant before being 
    used for tax filing, financial decisions, or regulatory compliance. This 
    software does not guarantee accuracy and is not a substitute for professional 
    accounting advice.
    """
    
    def __init__(self, user_id: int):
        self.user_id = user_id
    
    # =========================================================================
    # PROFIT & LOSS REPORT
    # =========================================================================
    
    def get_profit_and_loss(self, start_date: str, end_date: str, 
                            compare_previous: bool = False) -> Dict:
        """
        Generate a Profit & Loss (Income Statement) report.
        
        Args:
            start_date: Start date (YYYY-MM-DD)
            end_date: End date (YYYY-MM-DD)
            compare_previous: Include comparison to previous period
            
        Returns:
            Dict with income, expenses, and profit calculations
        """
        with get_db() as conn:
            cursor = conn.cursor()
            
            # === INCOME (Revenue) ===
            # Invoices marked as paid within the period
            cursor.execute('''
                SELECT 
                    COALESCE(SUM(subtotal), 0) as sales_revenue,
                    COALESCE(SUM(tax_amount), 0) as sales_tax_collected,
                    COALESCE(SUM(total), 0) as total_invoiced,
                    COUNT(*) as invoice_count
                FROM invoices
                WHERE user_id = ? 
                AND status = 'paid'
                AND paid_at BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            income_row = cursor.fetchone()
            
            # Get income by product/service category
            cursor.execute('''
                SELECT 
                    COALESCE(p.name, 'Uncategorized') as category,
                    SUM(ii.line_total) as amount
                FROM invoice_items ii
                JOIN invoices i ON ii.invoice_id = i.id
                LEFT JOIN products p ON ii.product_id = p.id
                WHERE i.user_id = ? 
                AND i.status = 'paid'
                AND i.paid_at BETWEEN ? AND ?
                GROUP BY p.name
                ORDER BY amount DESC
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            income_by_category = [dict(row) for row in cursor.fetchall()]
            
            # === EXPENSES ===
            # Bills paid within the period
            cursor.execute('''
                SELECT 
                    COALESCE(SUM(subtotal), 0) as bill_expenses,
                    COALESCE(SUM(tax_amount), 0) as bill_tax_paid,
                    COUNT(*) as bill_count
                FROM bills
                WHERE user_id = ? 
                AND status = 'paid'
                AND updated_at BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            bills_row = cursor.fetchone()
            
            # Expenses recorded within the period
            cursor.execute('''
                SELECT 
                    COALESCE(SUM(net_amount), 0) as expense_total,
                    COALESCE(SUM(tax_amount), 0) as expense_tax,
                    COUNT(*) as expense_count
                FROM expenses
                WHERE user_id = ? 
                AND status = 'approved'
                AND expense_date BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date))
            expenses_row = cursor.fetchone()
            
            # Get expenses by category
            cursor.execute('''
                SELECT 
                    COALESCE(category, 'Uncategorized') as category,
                    SUM(net_amount) as amount
                FROM expenses
                WHERE user_id = ? 
                AND status = 'approved'
                AND expense_date BETWEEN ? AND ?
                GROUP BY category
                ORDER BY amount DESC
            ''', (self.user_id, start_date, end_date))
            expenses_by_category = [dict(row) for row in cursor.fetchall()]
            
            # Get bill expenses by COA category
            cursor.execute('''
                SELECT 
                    COALESCE(coa.name, 'Uncategorized') as category,
                    SUM(bi.total) as amount
                FROM bill_items bi
                JOIN bills b ON bi.bill_id = b.id
                LEFT JOIN chart_of_accounts coa ON bi.coa_id = coa.id
                WHERE b.user_id = ? 
                AND b.status = 'paid'
                AND b.updated_at BETWEEN ? AND ?
                GROUP BY coa.name
                ORDER BY amount DESC
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            bill_expenses_by_category = [dict(row) for row in cursor.fetchall()]
            
            # === CREDIT NOTES (reduce revenue) ===
            cursor.execute('''
                SELECT 
                    COALESCE(SUM(subtotal), 0) as credit_notes_total,
                    COALESCE(SUM(tax_amount), 0) as credit_notes_tax,
                    COUNT(*) as credit_note_count
                FROM credit_notes
                WHERE user_id = ? 
                AND status IN ('issued', 'partial', 'applied')
                AND issue_date BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date))
            credit_row = cursor.fetchone()
            
            # === CALCULATIONS ===
            gross_revenue = float(income_row['sales_revenue'] or 0)
            credit_notes = float(credit_row['credit_notes_total'] or 0) if credit_row else 0
            net_revenue = gross_revenue - credit_notes
            
            total_expenses = (
                float(bills_row['bill_expenses'] or 0) + 
                float(expenses_row['expense_total'] or 0)
            )
            
            gross_profit = net_revenue - total_expenses
            
            # Tax calculations
            tax_collected = float(income_row['sales_tax_collected'] or 0)
            credit_note_tax = float(credit_row['credit_notes_tax'] or 0) if credit_row else 0
            net_tax_collected = tax_collected - credit_note_tax
            
            tax_paid = (
                float(bills_row['bill_tax_paid'] or 0) + 
                float(expenses_row['expense_tax'] or 0)
            )
            
            net_tax_position = net_tax_collected - tax_paid
            
            # === PREVIOUS PERIOD COMPARISON ===
            previous_period = None
            if compare_previous:
                # Calculate previous period dates - handle both string and date objects
                if isinstance(start_date, str):
                    start = datetime.strptime(start_date, '%Y-%m-%d')
                else:
                    start = datetime.combine(start_date, datetime.min.time())
                if isinstance(end_date, str):
                    end = datetime.strptime(end_date, '%Y-%m-%d')
                else:
                    end = datetime.combine(end_date, datetime.min.time())
                period_days = (end - start).days + 1
                prev_end = start - timedelta(days=1)
                prev_start = prev_end - timedelta(days=period_days - 1)
                
                previous_period = self.get_profit_and_loss(
                    prev_start.strftime('%Y-%m-%d'),
                    prev_end.strftime('%Y-%m-%d'),
                    compare_previous=False
                )
            
            return {
                'report_type': 'Profit & Loss',
                'period': {
                    'start_date': start_date,
                    'end_date': end_date
                },
                'disclaimer': self.DISCLAIMER,
                'generated_at': datetime.now().isoformat(),
                
                'income': {
                    'gross_revenue': gross_revenue,
                    'credit_notes': credit_notes,
                    'net_revenue': net_revenue,
                    'invoice_count': income_row['invoice_count'],
                    'credit_note_count': credit_row['credit_note_count'] if credit_row else 0,
                    'by_category': income_by_category
                },
                
                'expenses': {
                    'bills_total': float(bills_row['bill_expenses'] or 0),
                    'expenses_total': float(expenses_row['expense_total'] or 0),
                    'total_expenses': total_expenses,
                    'bill_count': bills_row['bill_count'],
                    'expense_count': expenses_row['expense_count'],
                    'by_category': expenses_by_category,
                    'bills_by_category': bill_expenses_by_category
                },
                
                'profit': {
                    'gross_profit': gross_profit,
                    'profit_margin': (gross_profit / net_revenue * 100) if net_revenue > 0 else 0
                },
                
                'tax': {
                    'collected': net_tax_collected,
                    'paid': tax_paid,
                    'net_position': net_tax_position,
                    'note': 'Positive = VAT owed to HMRC, Negative = VAT refund due'
                },
                
                'previous_period': previous_period
            }
    
    # =========================================================================
    # BALANCE SHEET
    # =========================================================================
    
    def get_balance_sheet(self, as_of_date: str) -> Dict:
        """
        Generate a Balance Sheet as of a specific date.
        
        Args:
            as_of_date: Date to generate balance sheet for (YYYY-MM-DD)
            
        Returns:
            Dict with assets, liabilities, and equity
        """
        config = get_db_config()
        is_mysql = config.get('type') == 'mysql'
        
        # Build aging CASE expression based on database type
        if is_mysql:
            ar_aging_case = f'''
                CASE 
                    WHEN DATEDIFF(%s, due_date) <= 0 THEN 'Current'
                    WHEN DATEDIFF(%s, due_date) <= 30 THEN '1-30 days'
                    WHEN DATEDIFF(%s, due_date) <= 60 THEN '31-60 days'
                    WHEN DATEDIFF(%s, due_date) <= 90 THEN '61-90 days'
                    ELSE '90+ days'
                END
            '''
            placeholder = '%s'
        else:
            ar_aging_case = '''
                CASE 
                    WHEN julianday(?) - julianday(due_date) <= 0 THEN 'Current'
                    WHEN julianday(?) - julianday(due_date) <= 30 THEN '1-30 days'
                    WHEN julianday(?) - julianday(due_date) <= 60 THEN '31-60 days'
                    WHEN julianday(?) - julianday(due_date) <= 90 THEN '61-90 days'
                    ELSE '90+ days'
                END
            '''
            placeholder = '?'
        
        with get_db() as conn:
            cursor = conn.cursor()
            
            # === ASSETS ===
            
            # Accounts Receivable (unpaid invoices)
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    COALESCE(SUM(total - amount_paid), 0) as accounts_receivable,
                    COUNT(*) as outstanding_invoices
                FROM invoices
                WHERE user_id = {placeholder}
                AND status IN ('sent', 'partial', 'overdue')
                AND issue_date <= {placeholder}
            ''', (self.user_id, as_of_date))
            ar_row = cursor.fetchone()
            accounts_receivable = float(ar_row['accounts_receivable'] or 0)
            
            # Accounts Receivable aging
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    {ar_aging_case} as aging_bucket,
                    SUM(total - amount_paid) as amount
                FROM invoices
                WHERE user_id = {placeholder}
                AND status IN ('sent', 'partial', 'overdue')
                AND issue_date <= {placeholder}
                GROUP BY aging_bucket
                ORDER BY 
                    CASE aging_bucket 
                        WHEN 'Current' THEN 1 
                        WHEN '1-30 days' THEN 2
                        WHEN '31-60 days' THEN 3
                        WHEN '61-90 days' THEN 4
                        ELSE 5
                    END
            ''', (as_of_date, as_of_date, as_of_date, as_of_date, self.user_id, as_of_date))
            ar_aging = [dict(row) for row in cursor.fetchall()]
            
            # === LIABILITIES ===
            
            # Accounts Payable (unpaid bills)
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    COALESCE(SUM(total - amount_paid), 0) as accounts_payable,
                    COUNT(*) as outstanding_bills
                FROM bills
                WHERE user_id = {placeholder}
                AND status IN ('approved', 'partial')
                AND bill_date <= {placeholder}
            ''', (self.user_id, as_of_date))
            ap_row = cursor.fetchone()
            accounts_payable = float(ap_row['accounts_payable'] or 0)
            
            # Accounts Payable aging
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    {ar_aging_case} as aging_bucket,
                    SUM(total - amount_paid) as amount
                FROM bills
                WHERE user_id = {placeholder}
                AND status IN ('approved', 'partial')
                AND bill_date <= {placeholder}
                GROUP BY aging_bucket
            ''', (as_of_date, as_of_date, as_of_date, as_of_date, self.user_id, as_of_date))
            ap_aging = [dict(row) for row in cursor.fetchall()]
            
            # Credit Notes Outstanding (liability - owed to customers)
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(total - amount_used), 0) as credit_notes_outstanding
                FROM credit_notes
                WHERE user_id = {placeholder}
                AND status IN ('issued', 'partial')
                AND issue_date <= {placeholder}
            ''', (self.user_id, as_of_date))
            cn_row = cursor.fetchone()
            credit_notes_outstanding = float(cn_row['credit_notes_outstanding'] or 0)
            
            # VAT/Tax Liability (estimated)
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    COALESCE(SUM(tax_amount), 0) as tax_collected
                FROM invoices
                WHERE user_id = {placeholder}
                AND status = 'paid'
                AND paid_at <= {placeholder}
            ''', (self.user_id, as_of_date + ' 23:59:59'))
            tax_collected = float(cursor.fetchone()['tax_collected'] or 0)
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(tax_amount), 0) as tax_paid
                FROM bills
                WHERE user_id = {placeholder} AND status = 'paid' AND updated_at <= {placeholder}
            ''', (self.user_id, as_of_date + ' 23:59:59'))
            tax_paid_bills = float(cursor.fetchone()['tax_paid'] or 0)
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(tax_amount), 0) as tax_paid
                FROM expenses
                WHERE user_id = {placeholder} AND status = 'approved' AND expense_date <= {placeholder}
            ''', (self.user_id, as_of_date))
            tax_paid_expenses = float(cursor.fetchone()['tax_paid'] or 0)
            
            estimated_tax_liability = tax_collected - tax_paid_bills - tax_paid_expenses
            
            # === EQUITY (Retained Earnings) ===
            # Calculate from all-time profit
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(subtotal), 0) as total_revenue
                FROM invoices
                WHERE user_id = {placeholder} AND status = 'paid' AND paid_at <= {placeholder}
            ''', (self.user_id, as_of_date + ' 23:59:59'))
            total_revenue = float(cursor.fetchone()['total_revenue'] or 0)
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(subtotal), 0) as total_credit_notes
                FROM credit_notes
                WHERE user_id = {placeholder} AND status IN ('issued', 'partial', 'applied') AND issue_date <= {placeholder}
            ''', (self.user_id, as_of_date))
            total_credit_notes = float(cursor.fetchone()['total_credit_notes'] or 0)
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(subtotal), 0) as total_bills
                FROM bills
                WHERE user_id = {placeholder} AND status = 'paid' AND updated_at <= {placeholder}
            ''', (self.user_id, as_of_date + ' 23:59:59'))
            total_bills = float(cursor.fetchone()['total_bills'] or 0)
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT COALESCE(SUM(net_amount), 0) as total_expenses
                FROM expenses
                WHERE user_id = {placeholder} AND status = 'approved' AND expense_date <= {placeholder}
            ''', (self.user_id, as_of_date))
            total_expenses = float(cursor.fetchone()['total_expenses'] or 0)
            
            retained_earnings = (total_revenue - total_credit_notes) - (total_bills + total_expenses)
            
            # === TOTALS ===
            total_assets = accounts_receivable
            total_liabilities = accounts_payable + credit_notes_outstanding + max(0, estimated_tax_liability)
            total_equity = retained_earnings
            
            return {
                'report_type': 'Balance Sheet',
                'as_of_date': as_of_date,
                'disclaimer': self.DISCLAIMER,
                'generated_at': datetime.now().isoformat(),
                
                'assets': {
                    'current_assets': {
                        'accounts_receivable': accounts_receivable,
                        'outstanding_invoices': ar_row['outstanding_invoices'],
                        'aging': ar_aging
                    },
                    'total_assets': total_assets,
                    'note': 'Cash and bank balances not tracked - please add from external sources'
                },
                
                'liabilities': {
                    'current_liabilities': {
                        'accounts_payable': accounts_payable,
                        'outstanding_bills': ap_row['outstanding_bills'],
                        'ap_aging': ap_aging,
                        'credit_notes_outstanding': credit_notes_outstanding,
                        'estimated_tax_liability': max(0, estimated_tax_liability)
                    },
                    'total_liabilities': total_liabilities
                },
                
                'equity': {
                    'retained_earnings': retained_earnings,
                    'total_equity': total_equity
                },
                
                'summary': {
                    'total_assets': total_assets,
                    'total_liabilities': total_liabilities,
                    'total_equity': total_equity,
                    'balance_check': round(total_assets - total_liabilities - total_equity, 2)
                }
            }
    
    # =========================================================================
    # TAX REPORTS
    # =========================================================================
    
    def get_vat_report(self, start_date: str, end_date: str) -> Dict:
        """
        Generate a VAT report for a tax period.
        
        ⚠️ This report MUST be verified by a qualified accountant before 
        submission to HMRC or any tax authority.
        
        Args:
            start_date: Start of VAT period (YYYY-MM-DD)
            end_date: End of VAT period (YYYY-MM-DD)
            
        Returns:
            Dict with VAT calculations following UK VAT return boxes
        """
        with get_db() as conn:
            cursor = conn.cursor()
            
            # Box 1: VAT due on sales (output tax)
            cursor.execute('''
                SELECT COALESCE(SUM(tax_amount), 0) as vat_on_sales
                FROM invoices
                WHERE user_id = ? 
                AND status = 'paid'
                AND paid_at BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            vat_on_sales = float(cursor.fetchone()['vat_on_sales'] or 0)
            
            # Deduct credit note VAT
            cursor.execute('''
                SELECT COALESCE(SUM(tax_amount), 0) as credit_note_vat
                FROM credit_notes
                WHERE user_id = ? 
                AND status IN ('issued', 'partial', 'applied')
                AND issue_date BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date))
            credit_note_vat = float(cursor.fetchone()['credit_note_vat'] or 0)
            
            box1 = vat_on_sales - credit_note_vat
            
            # Box 2: VAT due on acquisitions from EU (usually 0 for most small businesses)
            box2 = 0.0
            
            # Box 3: Total VAT due (Box 1 + Box 2)
            box3 = box1 + box2
            
            # Box 4: VAT reclaimed on purchases (input tax)
            cursor.execute('''
                SELECT COALESCE(SUM(tax_amount), 0) as vat_on_bills
                FROM bills
                WHERE user_id = ? 
                AND status = 'paid'
                AND updated_at BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            vat_on_bills = float(cursor.fetchone()['vat_on_bills'] or 0)
            
            cursor.execute('''
                SELECT COALESCE(SUM(tax_amount), 0) as vat_on_expenses
                FROM expenses
                WHERE user_id = ? 
                AND status = 'approved'
                AND expense_date BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date))
            vat_on_expenses = float(cursor.fetchone()['vat_on_expenses'] or 0)
            
            box4 = vat_on_bills + vat_on_expenses
            
            # Box 5: Net VAT to pay or reclaim
            box5 = box3 - box4
            
            # Box 6: Total value of sales (excluding VAT)
            cursor.execute('''
                SELECT COALESCE(SUM(subtotal), 0) as sales_value
                FROM invoices
                WHERE user_id = ? 
                AND status = 'paid'
                AND paid_at BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            sales_value = float(cursor.fetchone()['sales_value'] or 0)
            
            cursor.execute('''
                SELECT COALESCE(SUM(subtotal), 0) as credit_notes_value
                FROM credit_notes
                WHERE user_id = ? 
                AND status IN ('issued', 'partial', 'applied')
                AND issue_date BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date))
            credit_notes_value = float(cursor.fetchone()['credit_notes_value'] or 0)
            
            box6 = int(sales_value - credit_notes_value)  # Whole pounds
            
            # Box 7: Total value of purchases (excluding VAT)
            cursor.execute('''
                SELECT COALESCE(SUM(subtotal), 0) as bills_value
                FROM bills
                WHERE user_id = ? 
                AND status = 'paid'
                AND updated_at BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            bills_value = float(cursor.fetchone()['bills_value'] or 0)
            
            cursor.execute('''
                SELECT COALESCE(SUM(net_amount), 0) as expenses_value
                FROM expenses
                WHERE user_id = ? 
                AND status = 'approved'
                AND expense_date BETWEEN ? AND ?
            ''', (self.user_id, start_date, end_date))
            expenses_value = float(cursor.fetchone()['expenses_value'] or 0)
            
            box7 = int(bills_value + expenses_value)  # Whole pounds
            
            # Box 8 & 9: EU supplies (usually 0)
            box8 = 0
            box9 = 0
            
            # Get breakdown by VAT rate
            cursor.execute('''
                SELECT 
                    tax_rate,
                    SUM(subtotal) as net_amount,
                    SUM(tax_amount) as vat_amount
                FROM invoices
                WHERE user_id = ? 
                AND status = 'paid'
                AND paid_at BETWEEN ? AND ?
                GROUP BY tax_rate
                ORDER BY tax_rate DESC
            ''', (self.user_id, start_date, end_date + ' 23:59:59'))
            sales_by_rate = [dict(row) for row in cursor.fetchall()]
            
            return {
                'report_type': 'VAT Return',
                'period': {
                    'start_date': start_date,
                    'end_date': end_date
                },
                'disclaimer': self.DISCLAIMER + '''
                
⚠️ TAX REPORT WARNING: This VAT report is provided as a guide only. 
You MUST verify all figures with a qualified accountant or tax advisor 
before submitting to HMRC. Incorrect VAT returns may result in penalties.
                ''',
                'generated_at': datetime.now().isoformat(),
                
                'vat_return_boxes': {
                    'box1': round(box1, 2),
                    'box1_description': 'VAT due on sales and other outputs',
                    
                    'box2': round(box2, 2),
                    'box2_description': 'VAT due on acquisitions from EU member states',
                    
                    'box3': round(box3, 2),
                    'box3_description': 'Total VAT due (Box 1 + Box 2)',
                    
                    'box4': round(box4, 2),
                    'box4_description': 'VAT reclaimed on purchases and other inputs',
                    
                    'box5': round(box5, 2),
                    'box5_description': 'Net VAT to pay to HMRC (or reclaim)' if box5 >= 0 else 'Net VAT to reclaim from HMRC',
                    
                    'box6': box6,
                    'box6_description': 'Total value of sales, excluding VAT (whole pounds)',
                    
                    'box7': box7,
                    'box7_description': 'Total value of purchases, excluding VAT (whole pounds)',
                    
                    'box8': box8,
                    'box8_description': 'Total value of supplies to EU member states (whole pounds)',
                    
                    'box9': box9,
                    'box9_description': 'Total value of acquisitions from EU member states (whole pounds)'
                },
                
                'summary': {
                    'vat_collected': round(vat_on_sales, 2),
                    'credit_note_vat': round(credit_note_vat, 2),
                    'net_vat_on_sales': round(box1, 2),
                    'vat_on_bills': round(vat_on_bills, 2),
                    'vat_on_expenses': round(vat_on_expenses, 2),
                    'total_vat_reclaimable': round(box4, 2),
                    'net_vat_position': round(box5, 2),
                    'position': 'Pay to HMRC' if box5 > 0 else 'Reclaim from HMRC' if box5 < 0 else 'No VAT due'
                },
                
                'breakdown': {
                    'sales_by_vat_rate': sales_by_rate
                },
                
                'verification_checklist': [
                    '☐ Verify all sales invoices are correctly recorded',
                    '☐ Check all purchase invoices have valid VAT numbers',
                    '☐ Ensure credit notes are properly accounted for',
                    '☐ Confirm all expenses with VAT have valid receipts',
                    '☐ Review any partial exemption calculations if applicable',
                    '☐ Check for any reverse charge transactions',
                    '☐ Verify EU supply/acquisition figures if applicable',
                    '☐ Have figures reviewed by qualified accountant'
                ]
            }
    
    def get_income_tax_summary(self, tax_year_start: str, tax_year_end: str) -> Dict:
        """
        Generate an income tax summary for self-assessment.
        
        ⚠️ This report MUST be verified by a qualified accountant.
        
        Args:
            tax_year_start: Start of tax year (YYYY-MM-DD), usually 6 April
            tax_year_end: End of tax year (YYYY-MM-DD), usually 5 April
            
        Returns:
            Dict with income and expense summary for self-assessment
        """
        # Use P&L for the tax year period
        pl = self.get_profit_and_loss(tax_year_start, tax_year_end)
        
        return {
            'report_type': 'Income Tax Summary (Self-Employment)',
            'tax_year': {
                'start_date': tax_year_start,
                'end_date': tax_year_end
            },
            'disclaimer': self.DISCLAIMER + '''
            
⚠️ INCOME TAX WARNING: This summary is provided as a guide only for 
self-assessment tax returns. You MUST verify all figures with a qualified 
accountant or tax advisor before submitting to HMRC. The classification 
of expenses and income may vary based on your specific circumstances.
            ''',
            'generated_at': datetime.now().isoformat(),
            
            'turnover': {
                'gross_income': pl['income']['gross_revenue'],
                'less_credit_notes': pl['income']['credit_notes'],
                'net_turnover': pl['income']['net_revenue'],
                'note': 'This figure should go in Box 15 of the Self-Employment pages'
            },
            
            'allowable_expenses': {
                'cost_of_goods_sold': 0,  # Would need inventory tracking
                'bills_and_supplies': pl['expenses']['bills_total'],
                'other_expenses': pl['expenses']['expenses_total'],
                'total_allowable_expenses': pl['expenses']['total_expenses'],
                'note': 'Review each expense category to ensure they are allowable for tax purposes'
            },
            
            'profit': {
                'net_profit': pl['profit']['gross_profit'],
                'note': 'This is your taxable profit before any adjustments'
            },
            
            'expense_categories': pl['expenses']['by_category'],
            
            'reminders': [
                'Capital expenditure may need to be claimed as capital allowances',
                'Private use portions of expenses must be excluded',
                'Consider annual investment allowance for equipment purchases',
                'Keep all receipts and invoices for at least 6 years',
                'Declare all income including cash payments',
                'Consider making payments on account if profit exceeds threshold'
            ],
            
            'verification_required': True,
            'accountant_review_needed': True
        }
    
    # =========================================================================
    # AGED RECEIVABLES / PAYABLES REPORTS
    # =========================================================================
    
    def get_aged_receivables(self, as_of_date: str = None) -> Dict:
        """Get detailed aged receivables report."""
        if not as_of_date:
            as_of_date = date.today().isoformat()
        
        config = get_db_config()
        is_mysql = config.get('type') == 'mysql'
        placeholder = '%s' if is_mysql else '?'
        
        # Build date diff expression based on DB type
        if is_mysql:
            date_diff_expr = f"DATEDIFF(%s, i.due_date)"
        else:
            date_diff_expr = "julianday(?) - julianday(i.due_date)"
        
        with get_db() as conn:
            cursor = conn.cursor()
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    i.id, i.invoice_number, i.issue_date, i.due_date,
                    i.total, i.amount_paid, (i.total - i.amount_paid) as balance,
                    c.name as customer_name, c.email as customer_email,
                    {date_diff_expr} as days_overdue
                FROM invoices i
                LEFT JOIN customers c ON i.customer_id = c.id
                WHERE i.user_id = {placeholder}
                AND i.status IN ('sent', 'partial', 'overdue')
                AND (i.total - i.amount_paid) > 0.01
                ORDER BY i.due_date
            ''', (as_of_date, self.user_id))
            
            invoices = [dict(row) for row in cursor.fetchall()]
            
            # Categorize by aging bucket
            buckets = {
                'current': [],
                '1_30': [],
                '31_60': [],
                '61_90': [],
                'over_90': []
            }
            
            totals = {
                'current': 0,
                '1_30': 0,
                '31_60': 0,
                '61_90': 0,
                'over_90': 0,
                'total': 0
            }
            
            for inv in invoices:
                days = inv['days_overdue'] or 0
                balance = inv['balance']
                totals['total'] += balance
                
                if days <= 0:
                    buckets['current'].append(inv)
                    totals['current'] += balance
                elif days <= 30:
                    buckets['1_30'].append(inv)
                    totals['1_30'] += balance
                elif days <= 60:
                    buckets['31_60'].append(inv)
                    totals['31_60'] += balance
                elif days <= 90:
                    buckets['61_90'].append(inv)
                    totals['61_90'] += balance
                else:
                    buckets['over_90'].append(inv)
                    totals['over_90'] += balance
            
            return {
                'report_type': 'Aged Receivables',
                'as_of_date': as_of_date,
                'generated_at': datetime.now().isoformat(),
                'buckets': buckets,
                'totals': totals,
                'invoice_count': len(invoices)
            }
    
    def get_aged_payables(self, as_of_date: str = None) -> Dict:
        """Get detailed aged payables report."""
        if not as_of_date:
            as_of_date = date.today().isoformat()
        
        config = get_db_config()
        is_mysql = config.get('type') == 'mysql'
        placeholder = '%s' if is_mysql else '?'
        
        # Build date diff expression based on DB type
        if is_mysql:
            date_diff_expr = f"DATEDIFF(%s, b.due_date)"
        else:
            date_diff_expr = "julianday(?) - julianday(b.due_date)"
        
        with get_db() as conn:
            cursor = conn.cursor()
            
            cursor.execute(f'''  # nosemgrep: python.sqlalchemy.security.sqlalchemy-execute-raw-query.sqlalchemy-execute-raw-query -- column names come from a fixed list in this function; values are parameterised
                SELECT 
                    b.id, b.bill_number, b.reference, b.bill_date, b.due_date,
                    b.total, b.amount_paid, (b.total - b.amount_paid) as balance,
                    s.name as supplier_name, s.email as supplier_email,
                    {date_diff_expr} as days_overdue
                FROM bills b
                LEFT JOIN suppliers s ON b.supplier_id = s.id
                WHERE b.user_id = {placeholder}
                AND b.status IN ('approved', 'partial')
                AND (b.total - b.amount_paid) > 0.01
                ORDER BY b.due_date
            ''', (as_of_date, self.user_id))
            
            bills = [dict(row) for row in cursor.fetchall()]
            
            # Categorize by aging bucket
            buckets = {
                'current': [],
                '1_30': [],
                '31_60': [],
                '61_90': [],
                'over_90': []
            }
            
            totals = {
                'current': 0,
                '1_30': 0,
                '31_60': 0,
                '61_90': 0,
                'over_90': 0,
                'total': 0
            }
            
            for bill in bills:
                days = bill['days_overdue'] or 0
                balance = bill['balance']
                totals['total'] += balance
                
                if days <= 0:
                    buckets['current'].append(bill)
                    totals['current'] += balance
                elif days <= 30:
                    buckets['1_30'].append(bill)
                    totals['1_30'] += balance
                elif days <= 60:
                    buckets['31_60'].append(bill)
                    totals['31_60'] += balance
                elif days <= 90:
                    buckets['61_90'].append(bill)
                    totals['61_90'] += balance
                else:
                    buckets['over_90'].append(bill)
                    totals['over_90'] += balance
            
            return {
                'report_type': 'Aged Payables',
                'as_of_date': as_of_date,
                'generated_at': datetime.now().isoformat(),
                'buckets': buckets,
                'totals': totals,
                'bill_count': len(bills)
            }
